openapi: 3.0.0
info:
  title: Sample API
  description: A sample API to illustrate OpenAPI concepts
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Main (production) server
paths:
  /items:
    get:
      summary: List all items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
    post:
      summary: Create a new item
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Item created
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string